image: gitpod/workspace-python-3.11

tasks:
  # We want packages installed during the pre-build init steps to go to /workspace
  # rather than ~ so that they are persisted. Gitpod sets PIP_USER=yes to ensure this,
  # but pre-commit requires PIP_USER=no. Hence we set PIP_USER=no and use
  # pip install --user to install to /workspace.
  - name: kedro-plugins
    before: |
      echo PIP_USER=no >> ~/.bashrc && export PIP_USER=no
    init: |
      make sign-off
      pip install uv
      uv venv
      echo source .venv/bin/activate >> ~/.bashrc
      source ~/.bashrc
      make install-test-requirements plugin=kedro-datasets
    command: |
      pre-commit install --install-hooks
      clear

  - name: system
    init: |
      sudo apt-get update && sudo apt-get install -y --no-install-recommends libgl1 make
      sudo apt-get install -y --no-install-recommends libatk-bridge2.0-0 libcups2 ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
