# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
image: gitpod/workspace-python-3.12:2023-10-16-15-49-4


tasks:
  # We want packages installed during the pre-build init steps to go to /workspace
  # rather than ~ so that they are persisted. Gitpod sets PIP_USER=yes to ensure this,
  # but pre-commit requires PIP_USER=no. Hence we set PIP_USER=no and use
  # pip install --user to install to /workspace.
  - name: kedro-plugins
    before: |
      echo PIP_USER=no >> ~/.bashrc && export PIP_USER=no
    init: |
      make sign-off
    command: |
      pre-commit install --install-hooks
      clear


github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
