blank_issues_enabled: false
contact_links:
  - name: Slack workspace
    about: Come chat with the community!
    url: https://slack.kedro.org
  - name: Documentation
    url: https://docs.kedro.org
    about: To learn more about how Kedro works
  - name: Case studies, articles and video tutorials
    url: https://github.com/kedro-org/kedro-community
    about: Community-generated content, project examples and video tutorials
