# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH cd kedro-datasets && uv pip install .[docs]
      # Build the MkDocs documentation
      - cd kedro-datasets && mkdocs build
      # Ensure the output directory exists
      - mkdir --parents $READTHEDOCS_OUTPUT
      # Move the built site to the Read the Docs output directory
      - mv kedro-datasets/site/* $READTHEDOCS_OUTPUT/html

mkdocs:
  configuration: mkdocs.yml
