# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_install:
      - python -m pip install "uv==0.1.13"
      - export UV_HTTP_TIMEOUT=1000 && uv pip install --system --upgrade sphinx readthedocs-sphinx-ext "kedro-datasets[docs,test] @ ./kedro-datasets"
      - uv pip freeze
    pre_build:
      - python -m sphinx -WETan -j auto -D language=en -b linkcheck -d kedro-datasets/_build/doctrees kedro-datasets/docs/source kedro-datasets/_build/linkcheck
# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: kedro-datasets/docs/source/conf.py
  fail_on_warning: true

# TODO: Revert the hot fix with `pre_install` when pip release a better version.
# Optionally set the version of Python and requirements required to build your docs
# python:
#   install:
#     - method: pip
#       path: kedro-datasets
#       extra_requirements:
#         - docs
#         - test
