site_name: ""
site_url: https://docs.kedro.org/projects/kedro-datasets
repo_name: kedro-org/kedro-plugins
repo_url: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-datasets

theme:
  name: material
  custom_dir: docs/overrides/
  palette:
     # Palette toggle for light mode
    - scheme: light
      toggle:
        icon: material/white-balance-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: dark
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

  language: en
  font:
    text: Inter
    code: Inter Regular
  favicon: "https://kedro.org/images/favicon.ico"
  logo: assets/kedro_logo_black.svg
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/note-16
      tip: octicons/info-16
      warning: octicons/alert-16
      example: octicons/code-16

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.annotate
    - content.code.highlight

plugins:
  - search
  - autorefs
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: true
            show_source: false #currently doesn't show source at correct level, and not for pydantic models
            docstring_style: google
            merge_init_into_class: true
            docstring_section_style: list
            separate_signature: true
            show_root_heading: true
            docstring_options:
              ignore_init_summary: true
              warn_unknown_params: false
              returns_named_value: false
            paths: [src]
            import:
              - https://docs.kedro.org/en/stable/objects.inv
              - https://docs.kedro.org/projects/kedro-datasets/en/stable/objects.inv

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      title: Contents
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/colors.css
  - stylesheets/globals.css
  - stylesheets/typography.css
  - stylesheets/themes.css
  - stylesheets/footer.css
  - stylesheets/welcome.css

extra_javascript:
  - javascript/readthedocs.js
  - javascript/deindex-old-docs.js

nav:
  - Welcome: https://docs.kedro.org/en/develop/
  - Kedro: https://docs.kedro.org/en/develop/getting-started/course/
  - Kedro-Viz: https://docs.kedro.org/projects/kedro-viz/en/feature-12.0/
  - Kedro-Datasets:
    - API documentation:
      - Core Datasets:
        - api/kedro_datasets/index.md
        - api.APIDataset: api/kedro_datasets/api.APIDataset.md
        - biosequence.BioSequenceDataset: api/kedro_datasets/biosequence.BioSequenceDataset.md
        - dask.CSVDataset: api/kedro_datasets/dask.CSVDataset.md
        - dask.ParquetDataset: api/kedro_datasets/dask.ParquetDataset.md
        - databricks.ManagedTableDataset: api/kedro_datasets/databricks.ManagedTableDataset.md
        - email.EmailMessageDataset: api/kedro_datasets/email.EmailMessageDataset.md
        - geopandas.GenericDataset: api/kedro_datasets/geopandas.GenericDataset.md
        - holoviews.HoloviewsWriter: api/kedro_datasets/holoviews.HoloviewsWriter.md
        - huggingface.HFDataset: api/kedro_datasets/huggingface.HFDataset.md
        - huggingface.HFTransformerPipelineDataset: api/kedro_datasets/huggingface.HFTransformerPipelineDataset.md
        - ibis.FileDataset: api/kedro_datasets/ibis.FileDataset.md
        - ibis.TableDataset: api/kedro_datasets/ibis.TableDataset.md
        - json.JSONDataset: api/kedro_datasets/json.JSONDataset.md
        - matlab.MatlabDataset: api/kedro_datasets/matlab.MatlabDataset.md
        - matplotlib.MatplotlibDataset: api/kedro_datasets/matplotlib.MatplotlibDataset.md
        - matplotlib.MatplotlibWriter: api/kedro_datasets/matplotlib.MatplotlibWriter.md
        - networkx.GMLDataset: api/kedro_datasets/networkx.GMLDataset.md
        - networkx.GraphMLDataset: api/kedro_datasets/networkx.GraphMLDataset.md
        - networkx.JSONDataset: api/kedro_datasets/networkx.JSONDataset.md
        - pandas.CSVDataset: api/kedro_datasets/pandas.CSVDataset.md
        - pandas.DeltaTableDataset: api/kedro_datasets/pandas.DeltaTableDataset.md
        - pandas.ExcelDataset: api/kedro_datasets/pandas.ExcelDataset.md
        - pandas.FeatherDataset: api/kedro_datasets/pandas.FeatherDataset.md
        - pandas.GBQQueryDataset: api/kedro_datasets/pandas.GBQQueryDataset.md
        - pandas.GBQTableDataset: api/kedro_datasets/pandas.GBQTableDataset.md
        - pandas.GenericDataset: api/kedro_datasets/pandas.GenericDataset.md
        - pandas.HDFDataset: api/kedro_datasets/pandas.HDFDataset.md
        - pandas.JSONDataset: api/kedro_datasets/pandas.JSONDataset.md
        - pandas.ParquetDataset: api/kedro_datasets/pandas.ParquetDataset.md
        - pandas.SQLQueryDataset: api/kedro_datasets/pandas.SQLQueryDataset.md
        - pandas.SQLTableDataset: api/kedro_datasets/pandas.SQLTableDataset.md
        - pandas.XMLDataset: api/kedro_datasets/pandas.XMLDataset.md
        - partitions.IncrementalDataset: api/kedro_datasets/partitions.IncrementalDataset.md
        - partitions.PartitionedDataset: api/kedro_datasets/partitions.PartitionedDataset.md
        - pickle.PickleDataset: api/kedro_datasets/pickle.PickleDataset.md
        - pillow.ImageDataset: api/kedro_datasets/pillow.ImageDataset.md
        - plotly.HTMLDataset: api/kedro_datasets/plotly.HTMLDataset.md
        - plotly.JSONDataset: api/kedro_datasets/plotly.JSONDataset.md
        - plotly.PlotlyDataset: api/kedro_datasets/plotly.PlotlyDataset.md
        - polars.CSVDataset: api/kedro_datasets/polars.CSVDataset.md
        - polars.EagerPolarsDataset: api/kedro_datasets/polars.EagerPolarsDataset.md
        - polars.LazyPolarsDataset: api/kedro_datasets/polars.LazyPolarsDataset.md
        - redis.PickleDataset: api/kedro_datasets/redis.PickleDataset.md
        - snowflake.SnowparkTableDataset: api/kedro_datasets/snowflake.SnowparkTableDataset.md
        - spark.DeltaTableDataset: api/kedro_datasets/spark.DeltaTableDataset.md
        - spark.GBQQueryDataset: api/kedro_datasets/spark.GBQQueryDataset.md
        - spark.SparkDataset: api/kedro_datasets/spark.SparkDataset.md
        - spark.SparkHiveDataset: api/kedro_datasets/spark.SparkHiveDataset.md
        - spark.SparkJDBCDataset: api/kedro_datasets/spark.SparkJDBCDataset.md
        - spark.SparkStreamingDataset: api/kedro_datasets/spark.SparkStreamingDataset.md
        - svmlight.SVMLightDataset: api/kedro_datasets/svmlight.SVMLightDataset.md
        - tensorflow.TensorFlowModelDataset: api/kedro_datasets/tensorflow.TensorFlowModelDataset.md
        - text.TextDataset: api/kedro_datasets/text.TextDataset.md
        - yaml.YAMLDataset: api/kedro_datasets/yaml.YAMLDataset.md
      - Experimental Datasets:
        - api/kedro_datasets_experimental/index.md
        - databricks.ExternalTableDataset: api/kedro_datasets_experimental/databricks.ExternalTableDataset.md
        - langchain.ChatAnthropicDataset: api/kedro_datasets_experimental/langchain.ChatAnthropicDataset.md
        - langchain.ChatCohereDataset: api/kedro_datasets_experimental/langchain.ChatCohereDataset.md
        - langchain.ChatOpenAIDataset: api/kedro_datasets_experimental/langchain.ChatOpenAIDataset.md
        - langchain.OpenAIEmbeddingsDataset: api/kedro_datasets_experimental/langchain.OpenAIEmbeddingsDataset.md
        - netcdf.NetCDFDataset: api/kedro_datasets_experimental/netcdf.NetCDFDataset.md
        - prophet.ProphetModelDataset: api/kedro_datasets_experimental/prophet.ProphetModelDataset.md
        - pytorch.PyTorchDataset: api/kedro_datasets_experimental/pytorch.PyTorchDataset.md
        - rioxarray.GeoTIFFDataset: api/kedro_datasets_experimental/rioxarray.GeoTIFFDataset.md
        - safetensors.SafetensorsDataset: api/kedro_datasets_experimental/safetensors.SafetensorsDataset.md
        - video.VideoDataset: api/kedro_datasets_experimental/video.VideoDataset.md
