site_name: ""
site_url: https://docs.kedro.org/projects/kedro-datasets/en/stable/
repo_name: kedro-org/kedro-plugins
repo_url: https://github.com/kedro-org/kedro-plugins

theme:
  name: material
  custom_dir: docs/overrides/
  palette:
    # Palette toggle for light mode
    - scheme: light
      toggle:
        icon: material/white-balance-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: dark
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

  language: en
  font:
    text: Inter
    code: Inter Regular
  favicon: "https://kedro.org/images/favicon.ico"
  logo: assets/kedro_logo_black.svg
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/note-16
      tip: octicons/info-16
      warning: octicons/alert-16
      example: octicons/code-16

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.annotate
    - content.code.highlight

plugins:
  - search
  - autorefs
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: true
            show_source: false #currently doesn't show source at correct level, and not for pydantic models
            docstring_style: google
            merge_init_into_class: true
            docstring_section_style: list
            separate_signature: true
            show_root_heading: true
            docstring_options:
              ignore_init_summary: true
              warn_unknown_params: false
              returns_named_value: false
            paths: [src]
            import:
              - https://docs.kedro.org/en/stable/objects.inv
              - https://docs.kedro.org/projects/kedro-datasets/en/stable/objects.inv
  - llmstxt:
      markdown_description: |
        Kedro-Datasets provides a collection of data connectors for various file formats and storage systems,
        designed to work seamlessly with the Kedro framework's Data Catalog.

        This is a companion package to the main Kedro framework:
        Main documentation: https://docs.kedro.org/en/stable/

        Current version: 8.1.0
        Last updated: 21/08/2025

      full_output: llms-full.txt

      sections:
        Core Datasets Overview:
          - index.md: Kedro Datasets documentation homepage

        Core Data Format Datasets:
          - api/kedro_datasets/pandas.CSVDataset.md: CSV file handling with pandas
          - api/kedro_datasets/pandas.ExcelDataset.md: Excel file operations
          - api/kedro_datasets/pandas.ParquetDataset.md: Efficient columnar storage format
          - api/kedro_datasets/pandas.JSONDataset.md: JSON data handling
          - api/kedro_datasets/pandas.XMLDataset.md: XML file processing
          - api/kedro_datasets/pandas.HDFDataset.md: HDF5 file format support
          - api/kedro_datasets/pandas.FeatherDataset.md: Fast feather format
          - api/kedro_datasets/pandas.GenericDataset.md: Generic pandas operations
          - api/kedro_datasets/json.JSONDataset.md: Native JSON handling
          - api/kedro_datasets/yaml.YAMLDataset.md: YAML configuration files
          - api/kedro_datasets/text.TextDataset.md: Plain text file operations
          - api/kedro_datasets/pickle.PickleDataset.md: Python object serialization
          - api/kedro_datasets/biosequence.BioSequenceDataset.md: Biological sequence data
          - api/kedro_datasets/email.EmailMessageDataset.md: Email message handling
          - api/kedro_datasets/matlab.MatlabDataset.md: MATLAB file support
          - api/kedro_datasets/svmlight.SVMLightDataset.md: SVMLight format for ML
          - api/kedro_datasets/openxml.DocxDataset.md: Microsoft Word documents

        Database Datasets:
          - api/kedro_datasets/pandas.SQLTableDataset.md: SQL table operations
          - api/kedro_datasets/pandas.SQLQueryDataset.md: Custom SQL queries
          - api/kedro_datasets/pandas.GBQTableDataset.md: Google BigQuery tables
          - api/kedro_datasets/pandas.GBQQueryDataset.md: Google BigQuery queries
          - api/kedro_datasets/snowflake.SnowparkTableDataset.md: Snowflake integration
          - api/kedro_datasets/redis.PickleDataset.md: Redis key-value store

        Big Data and Distributed Computing:
          - api/kedro_datasets/spark.SparkDataset.md: Apache Spark DataFrames
          - api/kedro_datasets/spark.SparkHiveDataset.md: Spark Hive tables
          - api/kedro_datasets/spark.SparkJDBCDataset.md: Spark JDBC connections
          - api/kedro_datasets/spark.SparkStreamingDataset.md: Spark streaming data
          - api/kedro_datasets/spark.DeltaTableDataset.md: Delta Lake tables
          - api/kedro_datasets/spark.GBQQueryDataset.md: Spark BigQuery integration
          - api/kedro_datasets/databricks.ManagedTableDataset.md: Databricks managed tables
          - api/kedro_datasets/dask.CSVDataset.md: Dask distributed CSV
          - api/kedro_datasets/dask.ParquetDataset.md: Dask distributed Parquet
          - api/kedro_datasets/polars.CSVDataset.md: High-performance Polars CSV
          - api/kedro_datasets/polars.EagerPolarsDataset.md: Eager Polars DataFrames
          - api/kedro_datasets/polars.LazyPolarsDataset.md: Lazy Polars evaluation
          - api/kedro_datasets/pandas.DeltaTableDataset.md: Pandas Delta Lake support

        Partitioned and Incremental Data:
          - api/kedro_datasets/partitions.PartitionedDataset.md: Handle multiple files as one dataset
          - api/kedro_datasets/partitions.IncrementalDataset.md: Process only new/changed data

        Machine Learning and AI:
          - api/kedro_datasets/tensorflow.TensorFlowModelDataset.md: TensorFlow model storage
          - api/kedro_datasets/huggingface.HFDataset.md: HuggingFace datasets integration
          - api/kedro_datasets/huggingface.HFTransformerPipelineDataset.md: HuggingFace transformer pipelines

        Visualization and Plotting:
          - api/kedro_datasets/matplotlib.MatplotlibDataset.md: Matplotlib figure storage
          - api/kedro_datasets/plotly.PlotlyDataset.md: Interactive Plotly visualizations
          - api/kedro_datasets/plotly.JSONDataset.md: Plotly JSON format
          - api/kedro_datasets/plotly.HTMLDataset.md: Plotly HTML output
          - api/kedro_datasets/holoviews.HoloviewsWriter.md: Holoviews visualization
          - api/kedro_datasets/pillow.ImageDataset.md: Image processing with Pillow

        Geospatial and Scientific:
          - api/kedro_datasets/geopandas.GenericDataset.md: Geospatial data with GeoPandas
          - api/kedro_datasets/ibis.FileDataset.md: Ibis file operations
          - api/kedro_datasets/ibis.TableDataset.md: Ibis table operations
          - api/kedro_datasets/networkx.GMLDataset.md: Graph Modeling Language
          - api/kedro_datasets/networkx.GraphMLDataset.md: GraphML format
          - api/kedro_datasets/networkx.JSONDataset.md: NetworkX JSON graphs

        API and External Services:
          - api/kedro_datasets/api.APIDataset.md: REST API data fetching

        Experimental Datasets Overview:
          - api/kedro_datasets_experimental/index.md: Experimental features documentation

        Experimental LLM and AI:
          - api/kedro_datasets_experimental/langchain.ChatOpenAIDataset.md: OpenAI chat integration
          - api/kedro_datasets_experimental/langchain.ChatAnthropicDataset.md: Anthropic Claude integration
          - api/kedro_datasets_experimental/langchain.ChatCohereDataset.md: Cohere chat models
          - api/kedro_datasets_experimental/langchain.OpenAIEmbeddingsDataset.md: OpenAI embeddings
          - api/kedro_datasets_experimental/langchain.LangChainPromptDataset.md: LangChain prompt templates
          - api/kedro_datasets_experimental/langfuse.LangfusePromptDataset.md: Langfuse prompt integration
          - api/kedro_datasets_experimental/langfuse.LangfuseTraceDataset.md: Langfuse Tracing integration

        Experimental Deep Learning:
          - api/kedro_datasets_experimental/pytorch.PyTorchDataset.md: PyTorch model storage
          - api/kedro_datasets_experimental/safetensors.SafetensorsDataset.md: Safe tensor serialization

        Experimental Specialized Formats:
          - api/kedro_datasets_experimental/prophet.ProphetModelDataset.md: Time series with Prophet
          - api/kedro_datasets_experimental/video.VideoDataset.md: Video file processing
          - api/kedro_datasets_experimental/pypdf.PDFDataset.md: PDF file text extraction
          - api/kedro_datasets_experimental/netcdf.NetCDFDataset.md: NetCDF scientific data
          - api/kedro_datasets_experimental/rioxarray.GeoTIFFDataset.md: GeoTIFF raster data
          - api/kedro_datasets_experimental/polars.PolarsDatabaseDataset.md: Polars database connector
          - api/kedro_datasets_experimental/databricks.ExternalTableDataset.md: Databricks external tables

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      title: Contents
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/source-buttons.css
  - stylesheets/colors.css
  - stylesheets/globals.css
  - stylesheets/typography.css
  - stylesheets/themes.css
  - stylesheets/footer.css
  - stylesheets/welcome.css
  - stylesheets/code-select.css

extra_javascript:
  - javascript/readthedocs.js
  - javascript/deindex-old-docs.js
  - javascript/code-select.js
  - javascript/source-links.js

nav:
  - Welcome: https://docs.kedro.org/en/stable/
  - Kedro: https://docs.kedro.org/en/stable/getting-started/course/
  - Kedro-Viz: https://docs.kedro.org/projects/kedro-viz/en/stable/
  - Kedro-Datasets:
    - API documentation:
      - Core Datasets:
        - Overview: index.md
        - API:
          - api.APIDataset: api/kedro_datasets/api.APIDataset.md
        - Biosequence:
          - biosequence.BioSequenceDataset: api/kedro_datasets/biosequence.BioSequenceDataset.md
        - Dask:
          - dask.CSVDataset: api/kedro_datasets/dask.CSVDataset.md
          - dask.ParquetDataset: api/kedro_datasets/dask.ParquetDataset.md
        - Databricks:
          - databricks.ManagedTableDataset: api/kedro_datasets/databricks.ManagedTableDataset.md
        - Email:
          - email.EmailMessageDataset: api/kedro_datasets/email.EmailMessageDataset.md
        - Geopandas:
          - geopandas.GenericDataset: api/kedro_datasets/geopandas.GenericDataset.md
        - Holoviews:
          - holoviews.HoloviewsWriter: api/kedro_datasets/holoviews.HoloviewsWriter.md
        - Huggingface:
          - huggingface.HFDataset: api/kedro_datasets/huggingface.HFDataset.md
          - huggingface.HFTransformerPipelineDataset: api/kedro_datasets/huggingface.HFTransformerPipelineDataset.md
        - Ibis:
          - ibis.FileDataset: api/kedro_datasets/ibis.FileDataset.md
          - ibis.TableDataset: api/kedro_datasets/ibis.TableDataset.md
        - JSON:
          - json.JSONDataset: api/kedro_datasets/json.JSONDataset.md
        - Matlab:
          - matlab.MatlabDataset: api/kedro_datasets/matlab.MatlabDataset.md
        - Matplotlib:
          - matplotlib.MatplotlibDataset: api/kedro_datasets/matplotlib.MatplotlibDataset.md
        - NetworkX:
          - networkx.GMLDataset: api/kedro_datasets/networkx.GMLDataset.md
          - networkx.GraphMLDataset: api/kedro_datasets/networkx.GraphMLDataset.md
          - networkx.JSONDataset: api/kedro_datasets/networkx.JSONDataset.md
        - OpenXML:
          - docx.DocxDataset: api/kedro_datasets/openxml.DocxDataset.md
          - pptx.PptxDataset: api/kedro_datasets/openxml.PptxDataset.md
        - Pandas:
          - pandas.CSVDataset: api/kedro_datasets/pandas.CSVDataset.md
          - pandas.DeltaTableDataset: api/kedro_datasets/pandas.DeltaTableDataset.md
          - pandas.ExcelDataset: api/kedro_datasets/pandas.ExcelDataset.md
          - pandas.FeatherDataset: api/kedro_datasets/pandas.FeatherDataset.md
          - pandas.GBQQueryDataset: api/kedro_datasets/pandas.GBQQueryDataset.md
          - pandas.GBQTableDataset: api/kedro_datasets/pandas.GBQTableDataset.md
          - pandas.GenericDataset: api/kedro_datasets/pandas.GenericDataset.md
          - pandas.HDFDataset: api/kedro_datasets/pandas.HDFDataset.md
          - pandas.JSONDataset: api/kedro_datasets/pandas.JSONDataset.md
          - pandas.ParquetDataset: api/kedro_datasets/pandas.ParquetDataset.md
          - pandas.SQLQueryDataset: api/kedro_datasets/pandas.SQLQueryDataset.md
          - pandas.SQLTableDataset: api/kedro_datasets/pandas.SQLTableDataset.md
          - pandas.XMLDataset: api/kedro_datasets/pandas.XMLDataset.md
        - Partitions:
          - partitions.IncrementalDataset: api/kedro_datasets/partitions.IncrementalDataset.md
          - partitions.PartitionedDataset: api/kedro_datasets/partitions.PartitionedDataset.md
        - Pickle:
          - pickle.PickleDataset: api/kedro_datasets/pickle.PickleDataset.md
        - Pillow:
          - pillow.ImageDataset: api/kedro_datasets/pillow.ImageDataset.md
        - Plotly:
          - plotly.HTMLDataset: api/kedro_datasets/plotly.HTMLDataset.md
          - plotly.JSONDataset: api/kedro_datasets/plotly.JSONDataset.md
          - plotly.PlotlyDataset: api/kedro_datasets/plotly.PlotlyDataset.md
        - Polars:
          - polars.CSVDataset: api/kedro_datasets/polars.CSVDataset.md
          - polars.EagerPolarsDataset: api/kedro_datasets/polars.EagerPolarsDataset.md
          - polars.LazyPolarsDataset: api/kedro_datasets/polars.LazyPolarsDataset.md
        - Redis:
          - redis.PickleDataset: api/kedro_datasets/redis.PickleDataset.md
        - Snowflake:
          - snowflake.SnowparkTableDataset: api/kedro_datasets/snowflake.SnowparkTableDataset.md
        - Spark:
          - spark.DeltaTableDataset: api/kedro_datasets/spark.DeltaTableDataset.md
          - spark.GBQQueryDataset: api/kedro_datasets/spark.GBQQueryDataset.md
          - spark.SparkDataset: api/kedro_datasets/spark.SparkDataset.md
          - spark.SparkHiveDataset: api/kedro_datasets/spark.SparkHiveDataset.md
          - spark.SparkJDBCDataset: api/kedro_datasets/spark.SparkJDBCDataset.md
          - spark.SparkStreamingDataset: api/kedro_datasets/spark.SparkStreamingDataset.md
        - SVMLight:
          - svmlight.SVMLightDataset: api/kedro_datasets/svmlight.SVMLightDataset.md
        - TensorFlow:
          - tensorflow.TensorFlowModelDataset: api/kedro_datasets/tensorflow.TensorFlowModelDataset.md
        - Text:
          - text.TextDataset: api/kedro_datasets/text.TextDataset.md
        - YAML:
          - yaml.YAMLDataset: api/kedro_datasets/yaml.YAMLDataset.md
      - Experimental Datasets:
        - Overview: api/kedro_datasets_experimental/index.md
        - Databricks:
          - databricks.ExternalTableDataset: api/kedro_datasets_experimental/databricks.ExternalTableDataset.md
        - Langchain:
          - langchain.ChatAnthropicDataset: api/kedro_datasets_experimental/langchain.ChatAnthropicDataset.md
          - langchain.ChatCohereDataset: api/kedro_datasets_experimental/langchain.ChatCohereDataset.md
          - langchain.ChatOpenAIDataset: api/kedro_datasets_experimental/langchain.ChatOpenAIDataset.md
          - langchain.OpenAIEmbeddingsDataset: api/kedro_datasets_experimental/langchain.OpenAIEmbeddingsDataset.md
          - langchain.LangChainPromptDataset: api/kedro_datasets_experimental/langchain.LangChainPromptDataset.md
        - Langfuse:
          - langfuse.LangfusePromptDataset: api/kedro_datasets_experimental/langfuse.LangfusePromptDataset.md
          - langfuse.LangfuseTraceDataset: api/kedro_datasets_experimental/langfuse.LangfuseTraceDataset.md
        - NetCDF:
          - netcdf.NetCDFDataset: api/kedro_datasets_experimental/netcdf.NetCDFDataset.md
        - PyPDF:
          - pypdf.PDFDataset: api/kedro_datasets_experimental/pypdf.PDFDataset.md
        - Polars:
          - polars.PolarsDatabaseDataset: api/kedro_datasets_experimental/polars.PolarsDatabaseDataset.md
        - Prophet:
          - prophet.ProphetModelDataset: api/kedro_datasets_experimental/prophet.ProphetModelDataset.md
        - PyTorch:
          - pytorch.PyTorchDataset: api/kedro_datasets_experimental/pytorch.PyTorchDataset.md
        - RioXarray:
          - rioxarray.GeoTIFFDataset: api/kedro_datasets_experimental/rioxarray.GeoTIFFDataset.md
        - Safetensors:
          - safetensors.SafetensorsDataset: api/kedro_datasets_experimental/safetensors.SafetensorsDataset.md
        - Video:
          - video.VideoDataset: api/kedro_datasets_experimental/video.VideoDataset.md

not_in_nav: |
  readme.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
