name: Detect secrets on plugins

on:
  workflow_call:
    inputs:
      plugin:
        type: string
      os:
        type: string
      python-version:
        type: string

jobs:
  detect-secrets:
    defaults:
      run:
        shell: bash
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install the latest version of uv with Python ${{inputs.python-version}}
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: ${{ inputs.python-version }}
          activate-environment: true
      - name: Install dependencies
        run: |
          make plugin=${{ inputs.plugin }} install-lint-requirements
          uv pip freeze
      - name: Install pre-commit hooks
        run: |
          pre-commit install --install-hooks
          pre-commit install --hook-type pre-push
      - name: Scan all tracked files
        run: git ls-files ":(glob)*" ${{ inputs.plugin }} -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline
