name: Run Doc builds on Kedro-Datasets

on:
  push:
    branches:
      - main
      - try-rtd-build
    paths-ignore:
      - "kedro-airflow/**"
      - "kedro-docker/**"
      - "kedro-telemetry/**"
  pull_request:
    branches:
      - main
      - try-rtd-build
    paths-ignore:
      - "kedro-airflow/**"
      - "kedro-docker/**"
      - "kedro-telemetry/**"

jobs:
  datasets-test:
    uses: ./.github/workflows/check-plugin.yml
    with:
      plugin: kedro-datasets
